name: Snapshot Pipeline - #5

on: [push]

jobs:
  pipeline_config_load:
    runs-on: ubuntu-latest
    steps:
      - name: Load Config
        run: echo "Loading pipeline config..."

  build_snapshot_enterprise_intune:
    runs-on: ubuntu-latest
    # No 'needs' = runs parallel
    steps:
      - name: Build Snapshot
        run: echo "Building snapshot..."

  appdome_harden_snapshot:
    runs-on: ubuntu-latest
    # No 'needs' = runs parallel
    steps:
      - name: Harden Snapshot
        run: echo "Hardening snapshot..."
